### ISSUE TITLE
Setup CI to update doc book on pushes to main branch

### ISSUE THREAD

**Issue by kadenzipfel** [kadenzipfel/smart-contract-vulnerabilities#28]

**Comment by rakesh0x7** [comment]
Hi @kadenzipfel,

I'd like to work on this issue. Could you please assign it to me? Additionally, could you advise on what an appropriate commit message would be when the GitHub action runs?

**Comment by kadenzipfel** [comment]
@rakesh0x7 assigned! Thanks
