### ISSUE TITLE
Opcode Support/EVM Compatibility

### ISSUE THREAD

**Issue by indeqs** [kadenzipfel/smart-contract-vulnerabilities#37]
### Cross-Chain Opcode Support Variability Leading to Critical Bugs

**Issue Description:**
Deploying smart contracts across different blockchain environments can lead to critical bugs due to variations in opcode support. This issue was exemplified by the Gemholic project on zkSync Era, which encountered a significant problem when 921 ETH became locked due to the limitations of the `.transfer()` function.

**Detailed Analysis:**

**Case Study: Gemholic on zkSync Era**
- **Project**: GemstoneIDO, part of the Gemholic ecosystem.
- **Affected Network**: zkSync Era, an Ethereum Layer 2 scaling solution.
- **Specific Issue**: The GemstoneIDO contract used the `.transfer()` function, which is standard on Ethereum and other EVM-compatible chains. However, this function has limitations, particularly on zkSync Era. The `transfer()` function in Solidity is limited to 2300 gas, which can be insufficient if the receiving contract's fallback or receive function involves more complex logic. This can lead to the transaction reverting if the gas limit is exceeded.

**Impact:**
- **Locked Funds**: 921 ETH, raised during the Gemholic token sale became inaccessible because the contract deployment did not account for zkSync Era's handling of the `.transfer()` function.
- **Risk Exposure**: This incident highlights the broader risks of deploying smart contracts across different blockchain environments without fully understanding their specific opcode implementations and limitations.

**Root Cause:**
- **Opcode Support Variability**: While many blockchain platforms, including zkSync Era, are designed to be EVM-compatible, they may have variations in opcode support and gas handling that can affect contract functionality. The `.transfer()` function, in particular, is problematic in environments where gas costs for certain operations exceed the 2300 gas limit.

**References:**
- [GemstoneIDO Contract Issue Analysis on Medium](https://medium.com/coinmonks/gemstoneido-contract-stuck-with-921-eth-an-analysis-of-why-transfer-does-not-work-on-zksync-era-d5a01807227d)

**Comment by kadenzipfel** [comment]
This is a great vulnerability to add, but I think it would be better to give a more broad explanation, e.g. considering different opcode differences between chains and how it can cause issues, then after in a separate section we can focus in on this gemholic case study. I've added a style guide issue: https://github.com/kadenzipfel/smart-contract-vulnerabilities/issues/38 so that we can formatting expectations more clear.

Would also be good to note the use of push0 in solidity v0.8.22 and which chains may still not support it.

**Comment by kadenzipfel** [comment]
Closing as this has been replaced by https://github.com/kadenzipfel/smart-contract-vulnerabilities/issues/39
