### ISSUE TITLE
Proposal: Implement Pull Request Template

### ISSUE THREAD

**Issue by rakesh0x7** [kadenzipfel/smart-contract-vulnerabilities#43]
Hi, I'd like to propose adding a pull request template to this repository.

A pull request template can help contributors provide clear and consistent information about their changes, which can streamline the review process for everyone.

**Proposed Template:** I've included a draft pull request template below. We can modify it to fit the specific needs of this project.

![image](https://github.com/kadenzipfel/smart-contract-vulnerabilities/assets/60481830/2ba847e1-8414-41ed-b5bc-5d9c8383f7ce)

I'm open to discussing the proposed template and tailoring it to the specific needs of this project.

Please let me know your thoughts on implementing a pull request template.

**Comment by kadenzipfel** [comment]
Nice, yeah would be a great feature. I think we can drop the screenshots section though. Would also be good to add a template for issues, but in general I think we should aim to keep both simple

**Comment by rakesh0x7** [comment]
Hey @kadenzipfel ,

Thanks for the feedback on the pull request template! The simple and focused approach is definitely a good idea.

I've attached an updated pull request template (refer to the image) that incorporates your suggestions.  Do you have any further suggestions for improvement on the pull request template?
![Capture](https://github.com/kadenzipfel/smart-contract-vulnerabilities/assets/60481830/9c1a6431-aa40-4df8-9663-59bcf67b453a)
-----

For the issue template, I noticed you previously mentioned creating astyle-guide.md #38. In light of that, would you prefer the attached issue template (refer to the attached image) or a simpler version that references the style guide once it's complete?
![issue](https://github.com/kadenzipfel/smart-contract-vulnerabilities/assets/60481830/51381d0b-9e5c-472c-859c-9bb02c18c0a4)

Looking forward to hearing your thoughts!

**Comment by kadenzipfel** [comment]
@rakesh0x7, PR template looks great. Feel free to make a pull request to add it.

As for the issue template, I don't think issues need to be formatted super well, maybe instead it could have the user check a checkbox indicating that they've checked to see if the issue or feature being added exists already then could maybe have a "type of change" checkbox section like the PR template and then maybe just a section to explain the issue. What do you think?

**Comment by rakesh0x7** [comment]
>@rakesh0x7, PR template looks great. Feel free to make a pull request to add it.

sure, thanks.

>What do you think?

yeah, it's a good idea. I have created a sample issue template, could you please have a look

![Screenshot from 2024-05-21 22-20-01](https://github.com/kadenzipfel/smart-contract-vulnerabilities/assets/60481830/e4eb0405-784f-4c6e-81d7-8e5e28a2df35)

---
It will looks like this when someone clicks on new issue
![Screenshot from 2024-05-21 22-20-15](https://github.com/kadenzipfel/smart-contract-vulnerabilities/assets/60481830/846e2de0-cf2c-414a-94b5-e938cd657d2f)

---
Looking forward to hearing your thoughts!

**Comment by kadenzipfel** [comment]
@rakesh0x7, looks good! Feel free to submit a PR

**Comment by rakesh0x7** [comment]
@kadenzipfel, Thanks for confirming. Could you please assign it to me
