### ISSUE TITLE
Add index page to doc book

### ISSUE THREAD

**Issue by kadenzipfel** [kadenzipfel/smart-contract-vulnerabilities#50]
We should add a homepage/index to the [docbook](https://kadenzipfel.github.io/smart-contract-vulnerabilities/). I think we can just make that the README and it should already be well formatted. Will require updating: https://github.com/kadenzipfel/smart-contract-vulnerabilities/blob/master/.github/workflows/deploy-ghpages.yml

@rakesh0x7 is this something you'd be interested in doing?

**Comment by rakesh0x7** [comment]
>@rakesh0x7 is this something you'd be interested in doing?

Sure, I can handle adding the README as the homepage and updating the workflow. Please assign it to me.
