### ISSUE TITLE
Remove src directory from gh-pages Branch

### ISSUE THREAD

**Issue by rakesh0x7** [kadenzipfel/smart-contract-vulnerabilities#53]
The `src` directory in the `gh-pages` branch contains details about vulnerabilities that are not required for deployment purposes. The current GitHub workflow deploys the site directly from the main branch, making the `src` directory in the `gh-pages` branch redundant.

This will ensure that the `gh-pages` branch does not contain unnecessary information. The deployment process will remain unaffected as it is already configured to deploy from the `main` branch.

please let me know if it's okay for you. If so, please assign this issue to me so I can proceed with the necessary changes.

**Comment by kadenzipfel** [comment]
I'm not clear on what this changes. Does this just make the gh-pages file structure a bit cleaner?

**Comment by rakesh0x7** [comment]
@kadenzipfel yes, exactly. This change will make the file structure in the gh-pages branch cleaner by removing the unnecessary src directory.

**Comment by kadenzipfel** [comment]
IMO there's no real need to make this change
