### ISSUE TITLE
Add markdown syntax highlighting to all the code blocks.

### ISSUE THREAD

**Issue by 0xSandyy** [kadenzipfel/smart-contract-vulnerabilities#84]
## Checklist
- [x] I have searched the existing issues and pull requests for duplicates.

## Type of Issue
- [ ] New vulnerability addition
- [ ] Feature request
- [x] Update existing vulnerability

## Description
Hi, I was browsing through the repo and noticed that a lot of code blocks in the listings don't have any syntax highlighting for the code examples. Adding syntax highlight will make the code examples more readable and make the overall listing look good. I would like to open a PR to update all the code blocks inside the repo with proper syntax highlighting.

**Comment by kadenzipfel** [comment]
Added, thanks!
