### ISSUE TITLE
Update Insufficient Access Control vulnerability.

### ISSUE THREAD

**Issue by 0xSandyy** [kadenzipfel/smart-contract-vulnerabilities#85]
## Checklist
- [x] I have searched the existing issues and pull requests for duplicates.

## Type of Issue
- [ ] New vulnerability addition
- [ ] Feature request
- [x] Update existing vulnerability

## Description
The Insufficient Access Control vulnerability doesn't have much content inside it. Though Access Control Vulnerability is pretty straightforward, I think it will be worth mentioning all the common access control mechanisms that are used and some best practices like role based access control, 2 step role transfer, etc

**Comment by kadenzipfel** [comment]
Sounds good to me, feel free to open a PR
