### ISSUE TITLE
High level calls to EOA's

### ISSUE THREAD

**Issue by kadenzipfel** [kadenzipfel/smart-contract-vulnerabilities#88]
## Checklist
- [x] I have searched the existing issues and pull requests for duplicates.

## Type of Issue
- [x] New vulnerability addition
- [ ] Feature request
- [ ] Update existing vulnerability

## Description
High level calls are expected to revert the calling context if the call itself reverts. However, an unexpected case is executing high level calls on EOA's, which always silently succeeds. This is especially dangerous if the contract address is unset as this will effectively call an EOA.

## Additional Information
N/A

**Comment by 0xSandyy** [comment]
Hi, I was actually going to create an issue regarding this but it is more specific. If callback is called from a contract to an EOA, if the EOA doesn't implement the callback function, the function call reverts. And this is specially inside a try-catch block and even try catch block won't be able to catch this error. Therefore, address which is being called for callback should be verified to be a contract and callback on EOAs should be prevented.

**Comment by kadenzipfel** [comment]
Closing as I was confusing this with an actual issue which is that low-level calls will return successful if called to an EOA, but this is not the case for high level calls.
