### ISSUE TITLE
Update Links to Hyperlinks for Easy Access

### ISSUE THREAD

**Issue by rakesh0x7** [kadenzipfel/smart-contract-vulnerabilities#89]
## Checklist
- [X] I have searched the existing issues and pull requests for duplicates.

## Type of Issue
- [X] Update existing vulnerability

## Description
Currently, the links in the source section of all the vulnerability pages on the Smart Contract Vulnerabilities website (https://kadenzipfel.github.io/smart-contract-vulnerabilities/vulnerabilities/) are not clickable hyperlinks. Users have to copy and paste the URLs manually, which can be inconvenient.

## Proposed Solution:
Convert all plain text URLs in the source section to clickable hyperlinks. This will improve user experience by allowing users to click on the links directly.

**Comment by rakesh0x7** [comment]
@kadenzipfel please let me know your thought on this, so that I will make a PR

**Comment by 0xSandyy** [comment]
Hi @rakesh0x7, all the hyperlinks are available here: https://kadenzipfel.github.io/smart-contract-vulnerabilities/ or maybe i am missing something?

**Comment by rakesh0x7** [comment]
> Hi @rakesh0x7, all the hyperlinks are available here: https://kadenzipfel.github.io/smart-contract-vulnerabilities/ or maybe i am missing something?

I was referring to all plain text URLs in the source section.

![image](https://github.com/kadenzipfel/smart-contract-vulnerabilities/assets/60481830/39289c81-bf60-4a72-ab9b-56b3192693dd)

these are not clickable hyperlinks. Users have to copy and paste the URLs manually, which can be inconvenient.

---
I wanted to convert all plain text URLs in the source section to clickable hyperlinks, which I already did for [unencrypted-private-data-on-chain](https://kadenzipfel.github.io/smart-contract-vulnerabilities/vulnerabilities/unencrypted-private-data-on-chain.html)


![image](https://github.com/kadenzipfel/smart-contract-vulnerabilities/assets/60481830/e27632f6-7710-4639-b8d3-540f7cd4bf5d)

**Comment by 0xSandyy** [comment]
My bad. Good finding!

**Comment by rakesh0x7** [comment]
@kadenzipfel, Unfortunately, there isn't a direct way to open links in a new tab using just Markdown within the mdBook. Can I at least go with opening links on the same page?
